### ISSUE TITLE
#question#  How to calculate the network with a low pressure

### ISSUE THREAD

**Issue by ForestR** [mpimd-csc/morgen#2]
I am writing to ask if anyone know how to use `morgen` to deal with the natural gas pipeline network under low pressure environment (2kPa~10kPa). 

According to https://doi.org/10.1186/s13362-021-00109-4, the units for pressure and mass-flux are set as [Bar] and [kg/s] to homogenize scales. So there are some difficulties when we have to deal with end-consumption scenarios like neighborhoods or business districts.

Besides, compressible fluids may follow different equations of state to describe their behavior. There can be significant differences in the computation of compressible fluids, such as natural gas, when different boundary pressures are involved. 

Attached is the minute data of gas pipeline pressure in a business district.
[Examples of pressure time series.zip](https://github.com/mpimd-csc/morgen/files/11633868/Examples.of.pressure.time.series.zip)

**Comment by gramian** [comment]
Dear @ForestR ,
when designing and implementing `morgen` we were focusing on transport networks with higher pressures, and not low pressure distribution networks. So indeed, various details and Euler equation components would need to be adapted. Unfortunately, from the top of my head I don't know what changes would have to be made. However, I am sure generally `morgen` is applicable. Maybe the publication:

* Szoplik: [The Gas Transportation in a Pipeline Network](https://web.archive.org/web/20190502090054id_/https://cdn.intechopen.com/pdfs/35297.pdf)

has some relevant information?

Cheers

PS: The attached screenshot has no units attached to the y-axis, but I assume in your case the boundaries have to be more flexible than:

* pressure at inflows and mass-flux as outflows as boundaries,
* and mass-flux at inflows and pressures at outflows as computed quantites.

This is also possible in principle but not only the input and output operators need to be adapted but also the steady-state computation.

**Comment by ForestR** [comment]
Dear @gramian 

Thank you for the reply. I did some further research on the call of `morgen` and had some questions. Maybe you'd like to help me answer some questions.

1. Using a **relative pressure** of 2mbar to 10mbar would result in excessively small values, so I used the **absolute pressure** as the input to the boundary condition and set the flow rate of the output node to 0.0067kg/s (corresponding to 30m^3/h). I don't know how that affects the calculations.

2. In `utils/plot/plot_output.m`, I found that `solution.u(network.nSupply+1:end,:)` corresponds to the pressure of the outlet nodes and `solution.u(1:network.nSupply,:)` corresponds to the mass flow of the inlet nodes. I would like to ask how **the ordering of these nodes** is determined based on the `.net` file. This relates to the numeric configuration of the `.ini` file.

3. We can set the outlet mass flow of the specified node as zero and get the pressure of this node. And how to get the flow of the specified node (as opposed to the demand flow of the outlet node).

**Comment by gramian** [comment]
Hi @ForestR ,
1. Indeed the scenario boundaries are all encoded in sequences of absolute values. I think it should work though despite the scale difference.
2. The ordering is the sequence they are instantiated by edges defined in the network defintion `.net` file, see [here](https://github.com/mpimd-csc/morgen/blob/main/utils/format/format_network.m#L45) (lines 45--51). This codes scans the edge list for node indices appearing only once on the left (inflow) and on the right (outflow). This is the justification for the "[Network Topology Rules](https://github.com/mpimd-csc/morgen/tree/main#network-topology-rules)" (unfold). I would agree that this is not too obvious.
3. You would need to add manually another demand node with zero mass-flux in the scenario. Note, that this can screw up the order of boundary nodes in the network-scenario relation (see 2.). We did not consider this when building `morgen`, since we were aiming at model reduction of the known input-output mapping.

**Comment by ForestR** [comment]
Dear @gramian 

Thank you for reply. Although `morgen` is designed for model order reduction, it is the most user-friendly and extensible tools I have found for complex natural gas pipe network simulation. Based on some reasonable assumptions, the computational resources consumed by this work are also relatively low.

The 'morgen' platform therefore has potential value as a common benchmark for replicating simulation calculations for tasks such as optimization of pipeline networks, anomaly detection, machine learning, etc. This will facilitate communication and research in the field.

Maybe I could do a little bit of small work, such as a quick configuration of input/output nodes, to improve the usability of the tool.

**Comment by ForestR** [comment]
Dear @gramian 

Here are some new questions about the calculation:

1. Function of valves: I did not find the description of the edge type 'valve' in https://doi.org/10.1186/s13362-021-00109-4. Could it switch or It simply indicates a break in the connection?
2. Passive network: When all inlet sources/nodes are cut off by the valve, this creates a passive network. In this scenario, how should the boundary conditions of the model be set? This type of experimental design or data set is often involved in leak detection research (e.g., https://doi.org/10.1016/j.eswa.2023.120542; https://doi.org/10.1016/j.eswa.2022.118376).

**Comment by gramian** [comment]
Dear @ForestR ,

we are happy you find `morgen` useful for your purposes. Please feel free to fork our project.

However, the last paper related to the project funding this development is published now, and since development on this particular repository is concluded, it is likely that this repository will be archived.

To your question:

1. Valves were always planned but we never got to implement them. In terms of model reduction, valves pose quite a challenge; changing the network topology intraday (what `morgen` is meant to simulate) makes the underlying input-output system a switched nonlinear system for which the investigated reduction algorithms are not suited, at least not in their current form. Furthermore, from personal communications with domain experts, we were told that in regular operation intraday switching is rather rare. I see how this would be useful for leak or fault detection. And a static valve setting just defined constantly by the scenario would have introduced complexity (wrt to reduced order models and their training) we could not exploit, we ended up not implementing valves.

2. Given that the underlying input-output system is modeled by a system of first-order differential equations, I guess you should just set the inputs to zero. You probably deduced already that you would have to add an outflow at the leak position in the network. I have never tried that, so I cannot tell you what difficulties could be related to this. One thing I can imagine may lead to unphysical results is the following: In the steady-state computation we determine an averge pressure and mass-flux and center the system around these, as it improves the reduced order model for the nonlinear dynamics and simplifies computation. Now, a leak simulation likely diverges from this average and hence impacts simulation quality notably if not significantly.

Cheers
